# Generated by Django 5.1.7 on 2025-11-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_date_members_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='Member',
        ),
    ]
